image: heptacom/shopware-6-plugin-pipeline:php83-node20-latest

pipelines:
  default:
    - step: &github-mirror-branch
        name: Mirror to Github
        script:
          - git fetch origin
          - git remote add github https://x-token-auth:${GITHUB_TOKEN}@github.com/wimwenigerkind/satisfactory-server-docker.git
          - git push --force github ${BITBUCKET_BRANCH}
    -   step: &build-and-push-docker-image
          caches:
            - docker
          services:
            - docker
          name: Build and push docker image to Docker Hub
          image: debian:bookworm-slim
          script:
            - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
            - docker build -t "${DOCKER_USERNAME}/satisfactory-server-docker:latest" .
            - docker push "${DOCKER_USERNAME}/satisfactory-server-docker:latest"